//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Client.ClassServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClassServiceReference.IClassService")]
    public interface IClassService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/AddClass", ReplyAction="http://tempuri.org/IClassService/AddClassResponse")]
        void AddClass(SchoolManagement.Models.Class @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/AddClass", ReplyAction="http://tempuri.org/IClassService/AddClassResponse")]
        System.Threading.Tasks.Task AddClassAsync(SchoolManagement.Models.Class @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetClass", ReplyAction="http://tempuri.org/IClassService/GetClassResponse")]
        SchoolManagement.Models.Class GetClass(int classId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetClass", ReplyAction="http://tempuri.org/IClassService/GetClassResponse")]
        System.Threading.Tasks.Task<SchoolManagement.Models.Class> GetClassAsync(int classId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetAllClasses", ReplyAction="http://tempuri.org/IClassService/GetAllClassesResponse")]
        SchoolManagement.Models.Class[] GetAllClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetAllClasses", ReplyAction="http://tempuri.org/IClassService/GetAllClassesResponse")]
        System.Threading.Tasks.Task<SchoolManagement.Models.Class[]> GetAllClassesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/UpdateClass", ReplyAction="http://tempuri.org/IClassService/UpdateClassResponse")]
        void UpdateClass(SchoolManagement.Models.Class @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/UpdateClass", ReplyAction="http://tempuri.org/IClassService/UpdateClassResponse")]
        System.Threading.Tasks.Task UpdateClassAsync(SchoolManagement.Models.Class @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/DeleteClass", ReplyAction="http://tempuri.org/IClassService/DeleteClassResponse")]
        void DeleteClass(int classId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/DeleteClass", ReplyAction="http://tempuri.org/IClassService/DeleteClassResponse")]
        System.Threading.Tasks.Task DeleteClassAsync(int classId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassServiceChannel : SchoolManagement.Client.ClassServiceReference.IClassService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassServiceClient : System.ServiceModel.ClientBase<SchoolManagement.Client.ClassServiceReference.IClassService>, SchoolManagement.Client.ClassServiceReference.IClassService {
        
        public ClassServiceClient() {
        }
        
        public ClassServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddClass(SchoolManagement.Models.Class @class) {
            base.Channel.AddClass(@class);
        }
        
        public System.Threading.Tasks.Task AddClassAsync(SchoolManagement.Models.Class @class) {
            return base.Channel.AddClassAsync(@class);
        }
        
        public SchoolManagement.Models.Class GetClass(int classId) {
            return base.Channel.GetClass(classId);
        }
        
        public System.Threading.Tasks.Task<SchoolManagement.Models.Class> GetClassAsync(int classId) {
            return base.Channel.GetClassAsync(classId);
        }
        
        public SchoolManagement.Models.Class[] GetAllClasses() {
            return base.Channel.GetAllClasses();
        }
        
        public System.Threading.Tasks.Task<SchoolManagement.Models.Class[]> GetAllClassesAsync() {
            return base.Channel.GetAllClassesAsync();
        }
        
        public void UpdateClass(SchoolManagement.Models.Class @class) {
            base.Channel.UpdateClass(@class);
        }
        
        public System.Threading.Tasks.Task UpdateClassAsync(SchoolManagement.Models.Class @class) {
            return base.Channel.UpdateClassAsync(@class);
        }
        
        public void DeleteClass(int classId) {
            base.Channel.DeleteClass(classId);
        }
        
        public System.Threading.Tasks.Task DeleteClassAsync(int classId) {
            return base.Channel.DeleteClassAsync(classId);
        }
    }
}
